name: Build & deploy spring app

on:
  push:
    branches:
      - main
      # paths:
      #   -

jobs:
  build-deploy:
    name: Build and Deploy spring boot for beginner
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "corretto"
          java-version: 17

      - name: Unit Tests
        run: mvn -B test --file pom.xml
      # if you have several steps of unit test, use the pipe like
      #       - name: Unit Tests
      #         run: |
      #         mvn clean
      #         mvn -B test --file pom.xml

      - name: Build the appllication
        run: |
          mvn clean
          mvn -B package --file pom.xml

      - name: Build Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          dockfile: Dockerfile
          push: false #true it a test, we'll push it later
          tags: $ {{ secrets.DOCKER_HUB_USERNAME }}/spring-boot-for-beginners:latest
          # or tags: ${{ secrets.DOCKER_HUB_USERNAME }}/spring-boot-for-beginners:today
          # or tags: ${{ secrets.DOCKER_HUB_USERNAME }}/spring-boot-for-beginners:$(date-'%Y-%m-%d-%H-%M-%S') to get a date including hour, minutes, seconds

      - name: Login to Dcoker Hub
        uses: docker/login-action@v3
        with:
          username: $ {{ secrets.DOCKER_HUB_USERNAME }}
          password: $ {{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push to Dcoker Hub
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: $ {{ secrets.DOCKER_HUB_USERNAME }}/spring-boot-for-beginners:latest
